### PR TITLE
29825  reformat support request

### PR DESCRIPTION
**Pull request by k80bowman**
# Summary
Issue [#29825](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/29825)
Updating the support response Slack message to be more compact and highlight important info.

# Screenshots
image
(this was created using Slack's Block Kit playground)

### CODE REVIEW

**Comment by alexandec** [comment]
Nice, I think it's a big improvement! I did think of a couple changes that could make it even more compact. Something like:

> @RequestingPerson wrote: Here's my problem. A bunch of text here. Blah blah blah.
> Assigned to **FE Tools Team** (@katybowman)

That way it could all fit on two lines.

**Review by alexandec — APPROVED** [review]

**Comment by timwright12** [comment]
Would it be too cute to format it like a letter:
```
Dear @k80bowman (FE Tools),
I'm having trouble with my local build, is this where I would go to get some help?

Sincerely,
@timwright12 
```

**Comment by k80bowman** [comment]
@timwright12 I like it, but it might be a little too cute.

@alexandec I like this. Most messages are going to make it longer than two lines, but let me mock it up and run it past the Service Design team.

**Comment by k80bowman** [comment]
I played around a little and I came up with this.
image

The problem is that "Reassign Ticket" button. We need it, but whatever section it is attached to is made narrower by the width of whatever space the button takes up. So I like to have that bottom part be a separate section so that the button doesn't interfere with the main message.

**Comment by alexandec** [comment]
That makes total sense about the Reassign Ticket button. Seems like it works well in your latest mockup since the combination of username and team name will be short enough to leave space for the button. This mockup looks good to me!

One other thing I noticed: the support requests are always wrapped much earlier than normal Slack messages. Usually on Slack the text extends all the way to the edge of the window. Are the support requests different on purpose? On the plus side I think they're easier to read this way, but the bad part is that they take up more vertical space due to the wrapping.

**Comment by k80bowman** [comment]
Ooh, that is an excellent question. I hadn't even thought about that. I'll look into it, thanks!

**Comment by k80bowman** [comment]
@alexandec Ok, I have looked into the wrapping on the messages in Slack and I found out some interesting things. It looks like Slack adds a max-width to messages formatted with its Block Kit and there is really [no way to override it](https://stackoverflow.com/a/58805625). However, if you _don't_ use Block Kit and you just print the messages as plain text, then they wrap just like any normal message does. Which is great, except you lose any kind of formatting you might want to do to the text. So, say, someone wants to bold part of their message or add a code snippet or a link, that would no longer work.

I'm about six-to-one-half-dozen-to-the-other. On the one hand, it would be nice to get these messages to take up less space. On the other hand, people do use formatting features quite frequently and I would hate to lose that. I'm curious, though, what are your thoughts?

**Comment by alexandec** [comment]
Scrolling back through the channel, the most common formatting is clickable links, and then backticks in second place. As long as the links remain clickable, that part shouldn't be an issue. For backticks, if they show up like \`yarn install\`, that's not quite as nice but it's still readable I think.

If we also lose formatting for the "From" and "Assigned to" parts, that seems fine since I assume the @whatever part will still show up as a colorful link. We'd just lose the bold part. Maybe it's just my extreme minimalist self but I don't mind it, and the long lines would be pretty nice!

**Comment by k80bowman** [comment]
Ok, I'll take a look and see what happens. I'll need to get some things spun up locally to check this and make sure it works and see what it looks like, but I'll post a screen shot when I have it.

**Comment by k80bowman** [comment]
I was finally able to get back to this this morning! Unfortunately, though, @alexandec your idea won't work. At least not as long as we need the Reassign Ticket button.

Slack's API will allow us to print plain text _or_ Block Kit blocks, but not both. You can actually see this with our current bot. We have [a line](https://github.com/department-of-veterans-affairs/platform-support-slackbot/blob/56d592f8579e7febad6a224d328ee588fb2f822b/src/logic/form-support.js#L104) that is supposed to print as plain text now, but because we are using Block Kit, it does not print. I tested this out locally to see what would happen if I remove the Block Kit blocks, and that plain text message prints just fine.

**Comment by alexandec** [comment]
Ah well, thanks for looking into it! At least we can still shorten the requests compared to the existing format.

**Comment by k80bowman** [comment]
@alexandec I've updated the message to the shortened format, would you mind taking another look? Thanks!

**Comment by alexandec** [comment]
Looks great! The only thing I noticed is that the word "From" is bolded in the mockup, but doesn't look like it's bolded in the implementation.

**Comment by k80bowman** [comment]
Yeah, I accidentally forgot to bold it in the implementation, but I showed Rebekah a picture of it unbolded and she [commented](https://dsva.slack.com/archives/CPCGRR7F1/p1632323068081900?thread_ts=1631628497.043700&cid=CPCGRR7F1) on how she liked that in particular (having the name bolded, but not the word "From"). So I think it's OK. I should have pointed that out here, though.

**Pull request merged**
